-- Add missing OrderType enum values: PHONE, DELIVERY, HOTEL_ROOM
ALTER TABLE `Order` MODIFY COLUMN `type` ENUM('DINE_IN', 'TAKEAWAY', 'BANQUET', 'PHONE', 'DELIVERY', 'HOTEL_ROOM') NOT NULL DEFAULT 'DINE_IN';
