SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS stock_minimums;
DROP TABLE IF EXISTS event_package_items;
DROP TABLE IF EXISTS recipe_tags;
DROP TABLE IF EXISTS recipe_ingredients;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS products;
SET FOREIGN_KEY_CHECKS=1;
