SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS RecipeItem;
DROP TABLE IF EXISTS Recipe;
DROP TABLE IF EXISTS Ingredient;
DROP TABLE IF EXISTS recipe;
DROP TABLE IF EXISTS recipe_item;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS recipe_ingredients;
SET FOREIGN_KEY_CHECKS=1;
